server:
   port: 9002
   
spring:
   application:
      name: USER-SERVICE
   cloud:
      config:
         enabled: true
         uri: http://localhost:9200
eureka:
   instance:
      prefer-ip-address: true