server:
   port: 9000

spring:
   application:
      name: GATEWAY-SERVICE      
   cloud:
      gateway:
         routes:
            -  id: USER-SERVICE
               uri: lb://USER-SERVICE
               predicates: 
                  - Path=/user/**
            -  id: DEPARTMENT-SERVICE
               uri: lb://DEPARTMENT-SERVICE
               predicates: 
                  - Path=/department/**               
      config:
         enabled: true
         uri: http://localhost:9050
                       
eureka:
   instance:
      prefer-ip-address: true