server:
   port: 9050

spring:
   application:
      name: CONFIG-SERVER
   profiles:   
     active: native
   cloud:
      config:
         server:
            git:
               uri: https://github.com/chavannitin3/config-server
               clone-on-start: true
eureka:
   instance:
      prefer-ip-address: true